# Generated by Django 5.0.6 on 2025-07-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileMonitoring.folder'),
        ),
    ]
