# Generated by Django 5.0.6 on 2025-08-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileMonitoring', '0003_integritychecklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
